server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root    #hikari:      #minimum-idle: 1
      #maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
            - email
            - profile
          facebook:
            client-id: client-id
            client-secret: client-secret
            scope:
            - email
            - public_profile